#!/bin/bash

# Licensed to Datalayer (http://datalayer.io) under one or
# more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

docker rm -f datalayer-spitfire > /dev/null

if [ -z "$DATALAYER_DOCKER_DETACHED" ]
then
  export DATALAYER_DOCKER_DETACHED=true
fi

docker \
  run \
  -i \
  -t \
  -P \
  -p 2222:22 \
  -p 4040:4040 \
  -p 8080:8080 \
  -h spitfire.datalayer.io \
  -e JAVA_HOME=/opt/java \
  -e DOCKER_SPITFIRE_LOG_CONSOLE=true \
  -e SPITFIRE_HOME=/opt/datalayer-spitfire \
  -h docker.datalayer.io.local \
  --name datalayer-spitfire \
  --privileged \
  datalayer/spitfire:centos-6 "$@"
